[toBeCalled]
match='.toBeCalled'
rewrite='.toHaveBeenCalled'

[toBeCalledTimes]
match='.toBeCalledTimes'
rewrite='.toHaveBeenCalledTimes'

[toBeCalledWith]
match='.toBeCalledWith'
rewrite='.toHaveBeenCalledWith'

[lastCalledWith]
match='.lastCalledWith'
rewrite='.toHaveBeenLastCalledWith'

[nthCalledWith]
match='.nthCalledWith'
rewrite='.toHaveBeenNthCalledWith'

[toReturn]
match='.toReturn'
rewrite='.toHaveReturned'

[toReturnTimes]
match='.toReturnTimes'
rewrite='.toHaveReturnedTimes'

[toReturnWith]
match='.toReturnWith'
rewrite='.toHaveReturnedWith'

[lastReturnedWith]
match='.lastReturnedWith'
rewrite='.toHaveLastReturnedWith'

[nthReturnedWith]
match='.nthReturnedWith'
rewrite='.toHaveNthReturnedWith'

[toThrowError]
match='.toThrowError'
rewrite='.toThrow'






















